### ISSUE TITLE
Delete marshal PVC after run

### ISSUE THREAD

**Issue by StevenReitsma** [kubeflow-kale/kale#129]
When Kale creates a pipeline, it includes a step to create a marshal PVC for marshalling of data between pipeline steps. However, this PVC doesn't seem to be deleted after the run, which creates a lot of stale volumes. Would it be an idea to add a step to remove the marshal PVC as the final step in the pipeline?

**Comment by elikatsis** [comment]
Hello!

We are working on KFP-level garbage control, without the need for Kale specific code. You can take a look at kubeflow/pipelines#1779, as well as other issues/PRs referencing that.

We target KFP gc because, in any case, a PVC will not be deleted until all pods that mount it are deleted. Since workflows leave `Completed` pods behind upon completion, deleting PVCs will not lead to actual deletion.

**Comment by StevenReitsma** [comment]
That makes sense! Thanks for pointing me in the right direction. I'll follow the KFP issue and close this for now.
