### ISSUE TITLE
Incompatible kfp-server-api version and python version requirements incorrect

### ISSUE THREAD

**Issue by DavidSpek** [kubeflow-kale/kale#157]
While trying to incorporate kubeflow-kale into my notebook image I consistently get the error:
`ERROR: kfp 0.3.0 has requirement kfp-server-api<0.4.0,>=0.2.5, but you'll have kfp-server-api 0.1.18.3 which is incompatible.`
It seems there there is a discrepancy in the setup.py requirements. 

Also, the image I am using has python 3.8 installed by default, which should be supported as `python_requires='>=3.6.0'` has been specified. However, the requirement `'ml_metadata > 0.21, < 0.22'` creates an error with python 3.8 as ml_metadata is not available for python 3.8.

**Comment by elikatsis** [comment]
Hello,

Regarding the package `kfp-server-api`, we have pinned version `0.1.18.3` because that way we workaround these issues:
* https://github.com/kubeflow/pipelines/issues/2764
* https://github.com/kubeflow/pipelines/issues/3686
We don't make use of any newer client feature, so using that version is ok for us (the `ERROR` is more like a `WARNING`).
In the near future, Kale will target more recent KFP deployment versions and we will be fixing this.

For the python version, indeed it seems like `ml-metadata` isn't available for python 3.8 (https://pypi.org/project/ml-metadata/). We should check all packages and fix the `setup.py` accordingly.

**Comment by DavidSpek** [comment]
ml-metadata 0.24.0 was released 2 days ago and adds support for python 3.8 and fixes a grpcio bug that seems relevant. 
https://github.com/google/ml-metadata/releases/tag/v0.24.0
