### ISSUE TITLE
Not able to select ReadWriteOnce as Accessmode for PVC 

### ISSUE THREAD

**Issue by Hellekin87** [kubeflow-kale/kale#207]
Hello team,

we try to setup kale with kubeflow on our AWS EKS cluster using EBS as default StorageClass. When running the titanic example on our notebook with the default docker image the pipeline fails with the following error:
<pre>
<code>
Name:          titanic-ml-8onna-kw9z6-kale-marshal-pvc
Namespace:     kubeflow
StorageClass:  std-ebs-encrypted
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
               volume.kubernetes.io/selected-node: ip-xx-xx-xx-xx.eu-central-1.compute.internal
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    titanic-ml-8onna-kw9z6-1294320478
Events:
  Type     Reason                Age                    From                         Message
  ----     ------                ----                   ----                         -------
  Warning  ProvisioningFailed    7m50s (x459 over 17h)  persistentvolume-controller  Failed to provision volume with StorageClass "std-ebs-encrypted": invalid AccessModes [ReadWriteMany]: only AccessModes [ReadWriteOnce] are supported
  Normal   WaitForFirstConsumer  3m20s (x465 over 17h)  persistentvolume-controller  waiting for first consumer to be created before binding

</code></pre>

Kale always creates a marshall volume using the default StorageClass which in our case is EBS. 
During a quick research we found out that <code>ReadWriteOnce</code> is not support when using EBS. We already have EFS in place but couldn't define it as default StorageClass due to dependencies on other applications. Is there a way to define EFS as StorageClass just for Kale without having to change the default StorageClass?

Maybe an option directly integrated in the UI would be nice ;).

**Comment by DavidSpek** [comment]
I think you mixed up access modes as the error says you tried to create a `ReadWriteMany` volume while only `ReadWriteOnce` is supported for EBS. 

You can edit the `*.py` file that kale creates and edit `modes=dsl.VOLUME_MODE_RWM,` to `modes=dsl.VOLUME_MODE_RWO,`. This should enable support for ReadWriteOnce volumes as described here: https://github.com/kubeflow-kale/kale/issues/42. 

However, due to the volumes being ReadWriteOnce, you do loose out on parallel pipeline steps that use the same input data as only 1 pod can mount the volume at a time.
