### ISSUE TITLE
Kale examples are failing

### ISSUE THREAD

**Issue by raghulkrishna** [kubeflow-kale/kale#374]
All the kale examples are failing docker images is from docker/kale/Dockerfile
kubeflow deployed on eks without rok
i am getting the following error for all the sample experiments
can i have some input on this please ?
Thank you

![Screenshot 2021-09-25 at 9 55 29 PM](https://user-images.githubusercontent.com/62284209/134784541-da7b75b8-04bf-404c-a57c-37c7905cb242.png)

**Comment by palmoreck** [comment]
Hi there

Not sure if it's related with https://github.com/kubeflow-kale/kale/issues/377 because I'm installing some `tensorflow` packages ... maybe worth looking to `jupyter-client` version ...

The error that came out in my tests was:

```
  File "/usr/local/lib/python3.8/dist-packages/kale/common/jputils.py", line 210, in capture_streams
    msg_type = msg['header']['msg_type']
TypeError: 'coroutine' object is not subscriptable
/usr/lib/python3.8/threading.py:934: RuntimeWarning: coroutine 'ZMQSocketChannel.get_msg' was never awaited
  self._invoke_excepthook(self)
```

which is the same one of your screenshot @raghulkrishna 

@StefanoFioravanzo @elikatsis

Best 👋🏾
