### ISSUE TITLE
PVs stuck in pending state

### ISSUE THREAD

**Issue by velascoluis** [kubeflow-kale/kale#42]
Hi, first of all, congrats on this great initiative. Loving it so far.
Im experiencing some problems after running the automated generated pipelines, the pods seems to get unschedulable

![image](https://user-images.githubusercontent.com/57447519/72756950-05374a00-3bcf-11ea-9c02-42784b3158f0.png)

I checke on the GCP console, and found the PVs on pending state.

![image](https://user-images.githubusercontent.com/57447519/72756824-bc7f9100-3bce-11ea-9091-7f16b40e4639.png)

Hope you can help
Thanks
Luis

**Comment by elikatsis** [comment]
We're glad you like it!

The problem here is that your storage provisioner (`gce-pd`) doesn't support `ReadWriteMany` PVs.
Here's a workaround:
1. Retrieve the `.py` file generated by Kale (it should be next to the `.ipynb`)
2. Search for `marshal_vop` definition (`mashal_vop = dsl.VolumeOp...`)
3. Change this line `modes=dsl.VOLUME_MODE_RWM,` to `modes=dsl.VOLUME_MODE_RWO,`

**Comment by elikatsis** [comment]
Otherwise, you have to install some storage class that enables RWX volumes (e.g., some NFS provisioner) and set it as your cluster's default storage class.

**Comment by Shaked** [comment]
Is there a way to automatically generate the `.py` file with `RWO` instead of `RWM`?

**Comment by elikatsis** [comment]
Currently no, but it's a feature we will add

**Comment by velascoluis** [comment]
Solved by using FileStore in GCP (RWX) as suggested.
Thanks :)

**Comment by ca-scribner** [comment]
@elikatsis was this feature ever added?  I've got the related problem where my k8s default volume class supports only RWO.  I also have access to RWX volumes, but they're not the default.  Ideally I'd like to have settings somewhere that let me tell the marshal volume to be a different class
