### ISSUE TITLE
TF2.0 Kale in MiniKF 

### ISSUE THREAD

**Issue by Byest** [kubeflow-kale/kale#86]
Hi, I've installed MiniKF by following the tutorials on kubeflow.org. When creating a new notebook server, there are arrikto images (that include jupyterlab+kale) for TF 1.15, but not for 2.0. Is there any way to use Kale for TF 2.0+? Apologies if this is the wrong place to ask, or if the answer is really simple. Thank you~

**Comment by elikatsis** [comment]
Hi @Byest ! Thank you for using Kale and MiniKF.

Since you use MiniKF you also have Rok, which enables a number of functionalities.
One of them is library portability. If you select to use your notebook's volumes, Rok will take a snapshot of them and your pipeline steps will be using volumes clones out of these snapshots. That means that you can install any custom library (e.g., TF 2.0) and your pods will be able to use it, because it's actually installed in your workspace volume.

If you didn't use Rok, you would have to create a custom docker image for your notebook.

**Comment by Byest** [comment]
Thanks for the fast response, will try that. :)
